# This is the name of the workflow that will be displayed on GitHub.
name: Python Application CI

# This section defines the triggers for the workflow.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    # This strategy runs the job on multiple versions of Python.
    # It ensures your code is compatible across different environments.
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.10", "3.12"]

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Lint with ruff and check formatting with black
      run: |
        # Find style issues and potential errors.
        ruff check .
        # Verify that code formatting is correct without changing files.
        black --check .

    - name: Run tests
      #autorun pytest
      run: |
        pytest -v